In [10]:
MLFLOW_TRACKING_URI = '../models/mlruns'
MLFLOW_EXPERIMENT_NAME = "skills_jobs_stackoverflow"

NameError: name 'LOG_PATH' is not defined

In [42]:
import mlflow
from mlflow.tracking import MlflowClient

import pandas as pd

In [51]:
# Start a new run and track 
with mlflow.start_run(experiment_id=exp.experiment_id, 
                      run_name=model["model_description"]):
    # Log pickles
    mlflow.log_artifacts(LOG_PATH)  
    
    # Track metrics 
    for metric, score in mean_test_scores.items():
        mlflow.log_metric(metric, score)

NameError: name 'model' is not defined

In [43]:
# Initialize client
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
client = MlflowClient()

In [53]:
# Get experiment
experiment = client.get_experiment_by_name(MLFLOW_EXPERIMENT_NAME)
experiment

<Experiment: artifact_location='file:e:/Project/mlruns/445342063325317644', creation_time=1780093322556, experiment_id='445342063325317644', last_update_time=1780093322556, lifecycle_stage='active', name='my_experiment', tags={}, trace_location=None, workspace='default'>

In [45]:
print(experiment)

<Experiment: artifact_location='file:e:/Project/mlruns/445342063325317644', creation_time=1780093322556, experiment_id='445342063325317644', last_update_time=1780093322556, lifecycle_stage='active', name='my_experiment', tags={}, trace_location=None, workspace='default'>

In [54]:
# Get all runs
runs = mlflow.search_runs([experiment.experiment_id])
runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,tags.mlflow.runName,tags.mlflow.source.type,tags.mlflow.user,tags.mlflow.source.name
0,0b9f663b2e0947b3906a13f0f61a0302,445342063325317644,FAILED,file:e:/Project/mlruns/445342063325317644/0b9f...,2026-05-30 00:14:54.700000+00:00,2026-05-30 00:14:54.791000+00:00,my_model_run,NOTEBOOK,DELL,compare_models.ipynb
1,57cc94f0db824f398305cbafa6586ad4,445342063325317644,FAILED,file:e:/Project/mlruns/445342063325317644/57cc...,2026-05-29 23:38:54.989000+00:00,2026-05-29 23:38:55.101000+00:00,my_model_run,NOTEBOOK,DELL,compare_models.ipynb
2,f22601e6ad6d4443ac291b019b9a61a3,445342063325317644,FAILED,file:e:/Project/mlruns/445342063325317644/f226...,2026-05-29 23:26:21.466000+00:00,2026-05-29 23:26:21.529000+00:00,my_model_run,NOTEBOOK,DELL,compare_models.ipynb
3,b5c3bfd020664a9fad57829e121169aa,445342063325317644,FAILED,file:e:/Project/mlruns/445342063325317644/b5c3...,2026-05-29 22:22:02.972000+00:00,2026-05-29 22:22:03.031000+00:00,my_model_run,NOTEBOOK,DELL,compare_models.ipynb

In [56]:
import mlflow

runs = mlflow.search_runs(
    experiment_ids=["445342063325317644"]
)

runs[["run_id", "status"]]

                             run_id  status
0  0b9f663b2e0947b3906a13f0f61a0302  FAILED
1  57cc94f0db824f398305cbafa6586ad4  FAILED
2  f22601e6ad6d4443ac291b019b9a61a3  FAILED
3  b5c3bfd020664a9fad57829e121169aa  FAILED